### ISSUE TITLE
Save track selection

### ISSUE THREAD

**Issue by holandes22** [exercism/gui#14]
The app selector, being a component, gets destroyed on leaving the parent route. Store the selected
track in a service to store the state throughout the session

**Comment by mondayrain** [comment]
Came down with strep this past week so I haven't had a chance to do much other than sleep after work, but I still plan to do this! :)

**Comment by holandes22** [comment]
Sorry to hear, hope you get better soon :)

I had the CI mostly done, did a test release with packages built for Linux, Mac and Windows if you wanna give it a try https://github.com/holandes22/exercism-gui/releases/tag/v0.0.1-alpha.0

**Comment by mondayrain** [comment]
Awesome, the Mac package works for me! Awesome job 👍 
![mac_exercism_gui](https://cloud.githubusercontent.com/assets/4016519/16173087/21e7be5c-3564-11e6-8c1d-af485adba4c0.gif)

**Comment by holandes22** [comment]
Thank you. I noticed the track selection not working properly: the drop-down goes to the side, instead of falling directly beneath. No idea why is doing that, seems to only happen with the package from CI, when I build locally it works fine (on Linux for me)
