### ISSUE TITLE
Allow to fetch several or all problems for a track

### ISSUE THREAD

**Issue by holandes22** [exercism/gui#27]
Ground work for this was done at ticket #8 so implementation should be fairly easy. 

The reason to add this is explained in this ticket at the cli project https://github.com/exercism/cli/issues/335

Problem is that API does not support batch request for now so this requires making N request (one for each problem)

**Comment by Tonkpils** [comment]
I would love to tackle this if that's ok. Been wanting to do some work with Ember and Electron.

**Comment by holandes22** [comment]
Sure thing, that would be great!

Give it a try and send a PR when you are ready, was about to start on this after closing #28 but I'll hold off on it so you can tinker on it.

Some pointers to get you started:

This is basically the same as the fetch route but with several problems instead of one.
Take a look at:

- exercism.service.fetchSeveralAndSaveProblems()
- The template for the tracks.track.fetch route (this will need to be moved into a component to be used by the fetch-several route)

To start we can just fetch all the problems within a track, later on we can enhance it by giving the user the option to select which problems to fetch.

**Comment by holandes22** [comment]
@Tonkpils just a heads up, if you start working on this. I just opened a ticket to do a refactor to the exercism service (see #31 and the branch `ember-data-api` for more details.) Those changes will affect this ticket (I'll probably close #31  before the weekend)
