### ISSUE TITLE
Write install documentation

### ISSUE THREAD

**Issue by kytrinyx** [exercism/gui#48]
People don't know that there's a GUI for Exercism, since it's not documented on the site.

It would be useful to have a `/gui` page, that describes how to install it. We could then link to it in the places where we also link to the CLI documentation ('/cli').

See also:
- https://github.com/exercism/exercism.io/issues/3077
- https://github.com/exercism/exercism.io/issues/3442

**Comment by holandes22** [comment]
@kytrinyx thank you for opening this issue!. 
I'm preparing a PR for the exercism site to mention the GUI, but it has been going much slower than expected. I'll probably make some progress during the upcoming weekend.

**Comment by blueelvis** [comment]
@kytrinyx - I am confused on the part on what do I have to do? I mean what needs to be done with the Exercism Windows Installer?

**Comment by kytrinyx** [comment]
The Windows Installer is for the CLI right?

Currently, if someone comes to the website, how do they know that there is a GUI? If they want to install the GUI, how would they do that? Imagine that they aren't particularly familiar with GitHub, and they have never used Exercism. What steps would they need to take?

**Comment by blueelvis** [comment]
@kytrinyx - Yes, the Windows Installer is for the CLI. Should I create the documentation for the Windows Installer of CLI which could be added to the Exercism.io so people know that there is a Windows Installer for CLI as well.

Regarding the GUI, I will see what I can come up with :)

**Comment by kytrinyx** [comment]
> Yes, the Windows Installer is for the CLI.

OK! That helps. I've opened an issue https://github.com/exercism/exercism.io/issues/3466 about the windows installer.

This issue should be about the GUI.
