### ISSUE TITLE
Updating Windows PATH

### ISSUE THREAD

**Issue by robphoenix** [exercism/gui#53]
Hi, I posted a reply to https://github.com/exercism/exercism.io/issues/3077#issuecomment-290240995 a while back and @kytrinyx has asked me to move my question here:

> I just have a question; Is it supposed to add the exercism.exe to the PATH? It didn't on my machine and so adding C:\Program Files\Exercism to the path would have to be documented also. I don't know any C# but maybe this could become part of the installation in future versions? Adding things to the Windows PATH can often be a cause for mistakes for beginners, and tbh I'm still not immune from messing up my PATH!

**Comment by holandes22** [comment]
Hi,

I think there is a bit of a mix up here. Let me try to clarify. 

This repo is for the GUI client, which is in beta right now and not mentioned yet on the exercism site as I still need to write usage documentation (see #48). This GUI does not have an installer yet, it is distributed as a standalone isolated package (but an installer is planned, see #6)

There is another client, which is a command line tool and the one everyone uses, called the CLI client (repo [here](https://github.com/exercism/cli)),.

Now, it seems that there is also a separate project (https://github.com/exercism/windows-installer) that provides a Windows installer for the CLI client (I didn't know about it until you mentioned it). So I think this question is relevant to the windows-installer project. I went through their issues and this seems related to your specific question: https://github.com/exercism/windows-installer/issues/7 

Hope this helps

**Comment by blueelvis** [comment]
@robphoenix - The issue has been fixed in the latest release. I am still working on some minor things.

@holandes22 - Yes, the issue is in regards with the Windows Installer :)
